# nixpacks.toml for Laravel
[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "mysql-client"]

[phases.build]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
